name: API Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Start JSON Server
      - name: Start JSON Server
        run: |
          npx json-server employees.json --port 3000 &
        env:
          CI: true

      # Wait for JSON Server to be ready
      - name: Wait for JSON Server
        run: sleep 5

      # Run your API tests
      - name: Run API Tests
        run: |
          mvn clean test # Replace with your test command if different

      # Stop JSON Server
      - name: Stop JSON Server
        run: |
          kill $(lsof -t -i:3000)
